"""Create table for join token

Revision ID: f6b800fca5bf
Revises: 118b0b23489a
Create Date: 2022-07-19 23:18:27.744536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b800fca5bf'
down_revision = '118b0b23489a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
