"""Create table chat rooms

Revision ID: f79f5ed0a80f
Revises: 5b704199e140
Create Date: 2022-07-17 00:45:15.495980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79f5ed0a80f'
down_revision = '5b704199e140'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
